INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('1', 'x<=20', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('1', 'x>20 && x<3', '(30-x)/10');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('1', 'x>=30', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('2', 'x<=25', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('2', 'x>25 && x<35', '(x-25)/10');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('2', 'x>=35 && x<=45', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('2', 'x>45 && x<55', '(55-x)/10');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('2', 'x>=55', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('3', 'x<=50', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('3', 'x>50 && x<60', '(x-50)/10');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('3', 'x>=60', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('4', 'x<=6', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('4', 'x>6 && x<12', '(12-x)/6');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('4', 'x>=12', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('5', 'x<=9', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('5', 'x>9 && x<12', '(x-9)/3');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('5', 'x>=12 && x<=15', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('5', 'x>15 && x<18', '(18-x)/3');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('5', 'x>=18', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('6', 'x<=15', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('6', 'x>15 && x<18', '(x-15)/3');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('6', 'x>=18', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('7', 'x<=1', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('7', 'x>1 && x<2', '(2-x)/1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('7', 'x>=2', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('8', 'x<=3', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('8', 'x>1 && x<3', '(x-1)/2');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('8', 'x>=3 && x<=5', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('8', 'x>5 && x<7', '(7-x)/2');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('8', 'x>=7', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('9', 'x<=5', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('9', 'x>5 && x<7', '(x-5)/2');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('9', 'x>=7', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('10', 'x<=20', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('10', 'x>20 && x<40', '(40-x)/20');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('10', 'x>=40', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('11', 'x<=30', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('11', 'x>30 && x<40', '(x-30)/10');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('11', 'x>=40 && x<=60', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('11', 'x>60 && x<80', '(80-x)/20');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('11', 'x>=80', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('12', 'x<=60', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('12', 'x>60 && x<70', '(x-60)/10');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('12', 'x>=70 && x<=90', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('12', 'x>90 && x<100', '(100-x)/10');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('12', 'x>=100', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('13', 'x<=80', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('13', 'x>80 && x<100', '(x-80)/20');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('13', 'x>=100', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('14', 'x<=0', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('14', 'x>0 && x<1', '(1-x)/1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('14', 'x>=1', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('15', 'x<=0', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('15', 'x>0 && x<2', 'x/2');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('15', 'x>=2 && x<=4', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('15', 'x>4 && x<6', '(6-x)/2');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('15', 'x>=6', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('16', 'x<=3', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('16', 'x>3 && x<5', '(x-3)/2');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('16', 'x>=5 && x<=7', '1');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('16', 'x>7 && x<9', '(9-x)/2');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('16', 'x>=9', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('17', 'x<=7', '0');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('17', 'x>7 && x<9', '(x-7)/2');
INSERT INTO fungsi_keanggotaan (himpunan_id, fungsi, bobot) VALUES ('17', 'x>=9', '1');
